set nocompatible

call pathogen#infect()
call pathogen#helptags()

filetype plugin on
filetype indent on

" encoding
set encoding=utf8
set ffs=unix,dos,mac

" files
set nobackup
set nowb
set noswapfile

" syntax highlight color
syntax on

" color schema
set background=dark
if has("gui_running")
    color peaksea 
    set guifont=Menlo:h16
    "set guifont=Anonymous\ Pro:h16
    "set guioptions-=T
else
    color solarized
    "color ron
endif

" incremental search, <C-H> to toggle search highlight
set incsearch
map <silent><C-H> :set hls!<CR>
set ignorecase
set smartcase

" 4 spaces as tab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

" makefiles always use tab
autocmd FileType make setlocal noexpandtab

" indent
set autoindent
set smartindent
set wrap

" line number
map <C-N><C-N> :set nu!<CR>

" background
map <C-X><C-L> :set background=light<CR> :color solarized<CR>
map <C-X><C-D> :set background=dark<CR> :color peaksea<CR>

" invisible character
nmap <leader>l :set list!<CR>
set listchars=tab:▸-,eol:¬

" Format the statusline
set laststatus=2
set statusline=\ %F%m%r%h\ %w\ \ CWD:\ %r%{CurDir()}%h\ \ \ Line:\ %l/%L:%c
function! CurDir()
    let curdir = substitute(getcwd(), '/Users/erning/', "~/", "g")
    return curdir
endfunction

" Marked.app
:nnoremap <leader>m :silent !open -a Marked.app '%:p'<cr>

