# Functions to help us manage paths.  Second argument is the name of the
# path variable to be modified (default: PATH)
pathremove () {
    local IFS=':'
    local NEWPATH
    local DIR
    local PATHVARIABLE=${2:-PATH}
    for DIR in ${!PATHVARIABLE} ; do
        if [ "$DIR" != "$1" ] ; then
            NEWPATH=${NEWPATH:+$NEWPATH:}$DIR
        fi
    done
    export $PATHVARIABLE="$NEWPATH"
}

pathprepend () {
    pathremove $1 $2
    local PATHVARIABLE=${2:-PATH}
    export $PATHVARIABLE="$1${!PATHVARIABLE:+:${!PATHVARIABLE}}"
}

pathappend () {
    pathremove $1 $2
    local PATHVARIABLE=${2:-PATH}
    export $PATHVARIABLE="${!PATHVARIABLE:+${!PATHVARIABLE}:}$1"
}


# MacPorts
#pathprepend /opt/local/bin:/opt/local/sbin


# Utilities
#export ANDROID_SDK_HOME="${HOME}/apps/android-sdk-mac_x86"
export ANT_HOME="${HOME}/apps/apache-ant"
export M2_HOME="${HOME}/apps/apache-maven"

#export GOROOT="${HOME}/apps/go"
#export SCALA_HOME="${HOME}/apps/scala"
#export GROOVY_HOME="${HOME}/apps/groovy"

#pathprepend "${GROOVY_HOME}/bin"
#pathprepend "${SCALA_HOME}/bin"
#pathprepend "${GOROOT}/bin"
pathprepend "${M2_HOME}/bin"
pathprepend "${ANT_HOME}/bin"
#pathprepend "${ANDROID_SDK_HOME}/bin"

# golang
export GOPATH="${HOME}/apps/gopath"
pathprepend "${GOPATH}/bin"

# ~/bin
pathprepend "${HOME}/bin"

# Editor
export EDITOR="$HOME/bin/mvim -f"


# Tips and Tricks
export CDPATH=.:~
#export HISTIGNORE="&:ls:ls *:[bf]g:exit"


# bashrc
if [ -f "$HOME/.bashrc" ] ; then
  source $HOME/.bashrc
fi

# Now to clean up
unset pathremove pathprepend pathappend

# GPG always wants to know what TTY it's running on. 
export GPG_TTY=`tty`
